spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  threads:
    virtual:
      enabled: true
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  application:
    name: lab1
  datasource:
    url: jdbc:log4jdbc:sqlserver://localhost:1433;databaseName=GIBON;encrypt=false;trustServerCertificate=true
    username: admin
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#  mvc:
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/views/
#    static-path-pattern: /resources/**
  jpa:
    #database-platform: postgresql
    database: sqlserver
    hibernate:
      ddl-auto: none
      show_sql: true
    properties:
      hibernate:
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/**.xml
log4j:
  logger:
    org:
      mybatis:
        example: DEBUG
fileDir: C:/test/

#server:
#  ssl:
#    key-store: keystore.p12
#    key-store-type: PKCS12
#    key-store-password: no5685689
#  http2:
#    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"